language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_install: cd api
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coverage
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - npm install codeclimate-test-reporter && cat coverage/lcov.info | codeclimate-test-reporter